pullRequestPreviewsEnabled: true
pullRequestPreviewsExpireAfterDays: 3
services:
- type: web
  plan: starter plus
  previewPlan: starter
  name: express-backend
  env: node
  buildCommand: false
  startCommand: cd backend && yarn start
  envVars:
  - key: MY_API_KEY
    value: production-api-key
    previewValue: test-api-key
- type: web
  name: render-todo
  env: static
  buildCommand: cd frontend && yarn install && yarn build
  staticPublishPath: ./frontend/build
  envVars:
  - key: REACT_APP_API_HOST
    fromService:
      type: web
      name: express-backend
      property: host
