pullRequestPreviewsEnabled: true
pullRequestPreviewsExpireAfterDays: 3
services:
- type: web
  plan: starter plus
  previewPlan: starter
  name: express-backend
  env: node
  buildCommand: false
  startCommand: cd backend && yarn start
